// opml.js
//
// Parse and serialize OPML 2.0 subscription lists for the import/export
// flow in the Settings page. Browser-only — uses DOMParser. The Worker
// reads the parsed JSON shape, not OPML.
//
// Spec reference: http://opml.org/spec2.opml
//
// Round-trip contract:
//   parseOpml(serializeOpml(x)) ≈ x
// up to field ordering and the addition of a default <head><title> if the
// input lacks one. IDs and titles survive; URLs survive; folder structure
// survives one level (nested folders are flattened to "Folder / Sub").
//
// Exports:
//   parseOpml(text)              → { title, dateCreated, feeds[], folders[] }
//   serializeOpml(subscriptions) → OPML 2.0 XML string
//   subscriptionsFromOpml(opml)  → wrangler-ready { feeds:[{id,url,shelf}] }

const NS_NOTE = "Generated by CODA. https://github.com/Tiredicey/witch-hat-atelier";

// ─── Parse ─────────────────────────────────────────────────────────────────

export function parseOpml(text) {
  if (typeof text !== "string" || !text.trim()) {
    throw new Error("parseOpml: empty input");
  }
  const doc = new DOMParser().parseFromString(text, "application/xml");
  const err = doc.querySelector("parsererror");
  if (err) throw new Error("parseOpml: malformed XML");

  const root = doc.documentElement;
  if (!root || root.localName.toLowerCase() !== "opml") {
    throw new Error("parseOpml: not an OPML document");
  }

  const head = root.querySelector(":scope > head");
  const body = root.querySelector(":scope > body");
  if (!body) throw new Error("parseOpml: missing <body>");

  const title = head?.querySelector(":scope > title")?.textContent?.trim() || "";
  const dateCreated = head?.querySelector(":scope > dateCreated")?.textContent?.trim() || "";

  const feeds = [];
  const folders = [];

  function walk(node, folderPath) {
    for (const child of node.children) {
      if (child.tagName.toLowerCase() !== "outline") continue;
      const a = attrs(child);
      const hasUrl = !!a.xmlurl;
      const isFeed = a.type === "rss" || a.type === "atom" || hasUrl;
      if (isFeed && hasUrl) {
        feeds.push({
          id:    slugId(a.title || a.text || "", a.xmlurl, feeds.length),
          url:   a.xmlurl,
          title: a.title || a.text || "",
          htmlUrl: a.htmlurl || "",
          shelf: folderPath || "all",
        });
      } else {
        // folder
        const folderName = a.title || a.text || "Folder";
        const path = folderPath ? `${folderPath} / ${folderName}` : folderName;
        folders.push({ name: path });
        walk(child, path);
      }
    }
  }
  walk(body, "");

  return { title, dateCreated, feeds, folders };
}

// ─── Serialize ─────────────────────────────────────────────────────────────

export function serializeOpml({ title = "CODA subscriptions", feeds = [], folders = [] } = {}) {
  // Group feeds by shelf (treated as folder). Feeds with shelf="all" or no
  // shelf are emitted at the root of <body>.
  const groups = new Map();
  const root = [];
  for (const f of feeds) {
    const shelf = f.shelf && f.shelf !== "all" ? f.shelf : "";
    if (!shelf) { root.push(f); continue; }
    if (!groups.has(shelf)) groups.set(shelf, []);
    groups.get(shelf).push(f);
  }

  const lines = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  lines.push(`<opml version="2.0">`);
  lines.push(`  <head>`);
  lines.push(`    <title>${escapeXml(title)}</title>`);
  lines.push(`    <dateCreated>${new Date().toUTCString()}</dateCreated>`);
  lines.push(`    <ownerName>CODA</ownerName>`);
  lines.push(`    <docs>${NS_NOTE}</docs>`);
  lines.push(`  </head>`);
  lines.push(`  <body>`);
  for (const f of root) lines.push(feedOutline(f, "    "));
  for (const [name, list] of groups) {
    lines.push(`    <outline text="${escapeXml(name)}" title="${escapeXml(name)}">`);
    for (const f of list) lines.push(feedOutline(f, "      "));
    lines.push(`    </outline>`);
  }
  lines.push(`  </body>`);
  lines.push(`</opml>`);
  return lines.join("\n");
}

function feedOutline(f, indent) {
  const text = escapeXml(f.title || f.id || f.url);
  const html = f.htmlUrl ? ` htmlUrl="${escapeXml(f.htmlUrl)}"` : "";
  return `${indent}<outline text="${text}" title="${text}" type="rss" xmlUrl="${escapeXml(f.url)}"${html}/>`;
}

// ─── Helper: convert parsed OPML to the Worker FEEDS shape ─────────────────

export function subscriptionsFromOpml(parsed) {
  return {
    version: 1,
    updated: Date.now(),
    title:   parsed.title || "",
    feeds:   parsed.feeds.map(f => ({
      id:    f.id,
      url:   f.url,
      shelf: f.shelf || "all",
      title: f.title || "",
    })),
  };
}

// ─── Internals ─────────────────────────────────────────────────────────────

function attrs(el) {
  const out = {};
  for (const a of el.attributes) out[a.name.toLowerCase()] = a.value;
  return out;
}

function slugId(title, url, idx) {
  const t = (title || "").toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 30);
  if (t) return t;
  try {
    const u = new URL(url);
    const host = u.host.replace(/^www\./, "").replace(/[^a-z0-9]+/g, "-");
    return host || `feed-${idx}`;
  } catch {
    return `feed-${idx}`;
  }
}

function escapeXml(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
